### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by DNorell** [IOOPM-UU/course-web#4]
(Location: http://wrigstad.com/ioopm18/about.html#org399c919)

The link at `here` in the selected text from section 1.1 leads to `http://wrigstad.com/ioopm18/teams.html`, while that page is located at `http://wrigstad.com/ioopm18/team.html`.

Selected text:
>Stricter group meetings, with coachesAs described here.

**Comment by TobiasWrigstad** [comment]
Tack!
