### ISSUE TITLE
Ofullständig mening? Oklart om detta menar att vi ska använda google eller annat?

### ISSUE THREAD

**Issue by ROijvall** [IOOPM-UU/course-web#7]
(Location: http://wrigstad.com/ioopm18/assignments/assignment1.html)

Please describe the issue clearly, help me locate it on the page, and if possible suggest a fix.

Selected text:
>This is a good opportunity to use your search fu.

**Comment by DNorell** [comment]
Jag antar att `search fu` avser ens färdigheter att söka information, sannolikt inspirerat av ordet `kung fu`. Men jag förstår att det kan se ut som en ofullständig mening, jag insåg inte heller direkt att det (antagligen) inte var det.

**Comment by TobiasWrigstad** [comment]
Japp -- det är så det är tänkt. Lägger till en förklarande remark.
